### ISSUE TITLE
Strapi issue

### ISSUE THREAD

**Issue by IsabelDD** [VirtusLab/strapi-plugin-comments#14]
The issue is the following. I install the plugin and add a content type relation with my model Articles. 
I can post comments, edit comments, etc, by Postman. When I go to the secction of Strapi of collection Comments, I see the comments but when I tried to access to one of them I got an error from Strapi. 

This is the view of the comments I add 
![image](https://user-images.githubusercontent.com/67073580/100606613-fc90c380-3309-11eb-9dfe-057529d24898.png)

This is the error
![image](https://user-images.githubusercontent.com/67073580/100606989-8771be00-330a-11eb-8ef4-d84daf008710.png)

I tried to create all with the correct format and value by default, but I can find the error. I show you how I doing. 

![image](https://user-images.githubusercontent.com/67073580/100607187-d9b2df00-330a-11eb-9f44-f7f8cd0e82ed.png)

**Comment by cyp3rius** [comment]
@IsabelDD you've to use dedicated Comments Moderation UI accessible via: `Sidebar -> Plugins section -> Comments`. I'm not seeing it on the screenshots you've attached. Have you added plugin access for your role?

**Comment by IsabelDD** [comment]
I got this configuration in all the roles

![image](https://user-images.githubusercontent.com/67073580/100630364-c0ba2600-332a-11eb-9abc-9fc76373c64e.png)
![image](https://user-images.githubusercontent.com/67073580/100630407-cdd71500-332a-11eb-9fab-972adf7b3cd7.png)

And it's strange but I can't see the pluggin Comments on Strapi plugins section, but its collection is created and I can do all the calls. 

![image](https://user-images.githubusercontent.com/67073580/100630532-f4954b80-332a-11eb-9fdb-da4f1ca9c163.png)

**Comment by cyp3rius** [comment]
@IsabelDD as you mentioned you've added the collection by your own that seems. Not via installing the plugin through `npm` or `yarn` please refer to the README.md section. After successful installation and adding relation to your own content types you should see the following screen.

<img width="1440" alt="Zrzut ekranu 2020-11-30 o 21 41 32" src="https://user-images.githubusercontent.com/11504214/100662785-a8abcc00-3355-11eb-81c8-a671d9a46085.png">

As you can notice, in the left menu there is separated option "Plugins -> Comments". There is the moderation panel, of course you'll see the Comments, Reports collections as you won't hide them via RBAC plugin (Strapi enhancement with hiding plugin collections is in progress).

**Comment by IsabelDD** [comment]
I read the readme, I got the version 3.3.3 of Strapi. Here is the folder where I got the Strapi environment and where via console I install the plugin 
![image](https://user-images.githubusercontent.com/67073580/100709159-e4728000-33ad-11eb-9c51-43b45582d168.png)

![image](https://user-images.githubusercontent.com/67073580/100709209-f9e7aa00-33ad-11eb-911d-cdfdecb8bbe8.png)

When I made that instalation I run Strapi.  I got a Collection called comments only. 
![image](https://user-images.githubusercontent.com/67073580/100709344-374c3780-33ae-11eb-978c-288136cef100.png)

I add the relation to my own content types, this case, articles on the file settings.json of my model inside the atributes 
![image](https://user-images.githubusercontent.com/67073580/100709619-b93c6080-33ae-11eb-8bed-c2f295327218.png)

I start the Strapi environment again. I have on my collection that I change the attribute but I can see what you say on the section comments. 

![image](https://user-images.githubusercontent.com/67073580/100709772-f7d21b00-33ae-11eb-91b3-3aa305f0b0b6.png)

Maybe I install in the wrong path? But I follow your instruction of the README and I can do the calls of the API. Moreover when I add a comment via POST call I can't access in the Comments collection like I said at the beggining. I very interesting on using this plugin, but I don't understand why the impletation was not been the correct.

**Comment by cyp3rius** [comment]
@IsabelDD that seems you're just running `yarn develop`. Strapi after installing the plugins by default is not rebuilding it admin tool. To trigger that after installation of new dependency (plugin, extension) you've to run `yarn build` and then `yarn develop` to get brand new package and pull all the dependencies. Or simply for development use `yarn develop --watch-admin` (following Strapi docs) to get dependencies being pulled in a runtime.

Strapi Admin UI is independent from API so that's the reason you've been able to access API but not the UI.

I've done the steps I described with fresh Strapi instance and works as expected. Hope that helps.

**Comment by IsabelDD** [comment]
NOW! YES! But i have the same problem in the Comments section
![image](https://user-images.githubusercontent.com/67073580/100739715-ccaff180-33d7-11eb-815e-892b01f46f3f.png)

when I tried to access to one of the comments I got and error. The first image is what i see and the second is when i made click on one of them.
![image](https://user-images.githubusercontent.com/67073580/100739945-34663c80-33d8-11eb-9e70-03ad85bdb0a7.png)

![image](https://user-images.githubusercontent.com/67073580/100739912-23b5c680-33d8-11eb-8743-fd76fea97588.png)

**Comment by cyp3rius** [comment]
As I mentioned above:

As you can notice, in the left menu there is separated option "Plugins -> Comments". There is the moderation panel, of course you'll see the Comments, Reports collections as you won't hide them via RBAC plugin (Strapi enhancement with hiding plugin collections is in progress).

Strapi Content Manager is not supporting hidden collections (dedicated for plugins), both Comments, Reports shouldn't be managed via Content Manager as it is not supporting the functionalities and checks provided by plugin. That's expected behavior.

Please use only the Moderation UI delivered with plugin.

**Comment by IsabelDD** [comment]
Thanks! I understand! Thank you so much for your time and congrats for this plugin :)

**Comment by cyp3rius** [comment]
No probs, you're welcome :)

**Comment by mikekoro** [comment]
Having a somewhat related issue. I get the following error message when I go to "Plugins" -> "Comments" -> Comment I just posted.

``error InternalServerError: Cast to ObjectId failed for value "5" at path "_id" for model "comment"``

<img width="1446" alt="Screen Shot 2020-12-05 at 11 28 13 AM" src="https://user-images.githubusercontent.com/2127545/101255567-070fea80-375a-11eb-96b9-65fb0e663a97.png">

This is what I POST to create a new comment (not sure maybe thats where the issue is?)

```
{
    "authorUser": "5fb48e746b458f4dc1da0751",
	"content": "My sample response",
	"related": [{
		"refId": "5fcba9fee5e1787e022cf178",
		"ref": "post",
		"field": "comments"
	}]
}
```
refId is the ID of the post I am trying to comment on. Same ID is being supplied via the endpoint: 

``POST http://localhost:1337/comments/post:5fcba9fee5e1787e022cf178`` (not sure if it needs to be supplied in both places: URL and the body of the request)

When I go to that post I can definitely see that the new comment was "propagated":

<img width="344" alt="Screen Shot 2020-12-05 at 11 35 19 AM" src="https://user-images.githubusercontent.com/2127545/101258074-f14ef500-375a-11eb-9091-9535d104abaa.png">

Any ideas?

**Comment by ibnumubarok** [comment]
> Having a somewhat related issue. I get the following error message when I go to "Plugins" -> "Comments" -> Comment I just posted.
> 
> `error InternalServerError: Cast to ObjectId failed for value "5" at path "_id" for model "comment"`
> 


I'm also having the same error. I tried to recreate this on a new fresh strapi setup, and it produced the error, as you can see from this youtube url https://youtu.be/rmou2Ah5Ar8 (a 7 minutes video long, so you might skip to see the important parts)

I might miss some steps or configuration, or even misunderstood how to use this plugin, so any feedback, I really appreciate it. thanks.

**Comment by cyp3rius** [comment]
@mikekoro @ibnumubarok created separated issue for this as not related to this one. Let's discuss there.
