### ISSUE TITLE
Help Error 403 Forbidden 

### ISSUE THREAD

**Issue by RaimonxDev** [VirtusLab/strapi-plugin-comments#37]
Hi, I'm testing with postman but I can't create the first comment, I have to enable the endpoind but I don't know where. I already tried with roles and permissions but it doesn't work. do I need to do something else?

![image](https://user-images.githubusercontent.com/39868803/106004239-c6fe2180-6091-11eb-86b6-c5365f55df94.png)

here the roles and permissions. and the content type where I added the comments

![image](https://user-images.githubusercontent.com/39868803/106004506-0cbaea00-6092-11eb-9f09-b3ba592d5582.png)

![image](https://user-images.githubusercontent.com/39868803/106004769-4f7cc200-6092-11eb-81c9-6db3e3c9951f.png)

**Comment by cyp3rius** [comment]
@RaimonxDev the way you're doing it is entirely correct, but as I see you've allowed `post` action only. Enable please following actions:

- `findallflat`
- `findallinhierarchy`
- `pointsup`
- `post`
- `put`
- `reportabuse`

That will unlock the full scope of functionalities via REST API and you'll be able to make a GET request. The case in your query is also this that you've prepared a body for POST call but you're trying to perform GET on same endpoints. That's the root cause of 403 here. Change the action to POST and all should work even now :)

**Comment by RaimonxDev** [comment]
Thanks it worked

**Comment by cyp3rius** [comment]
@RaimonxDev refer to the Readme first please. We strictly recommend to not use Comments in Collection Types but Plugins -> Comments as its dedicated moderation panel.

Strapi by default is not supporting such advanced features as Plugins delivers.

**Comment by RaimonxDev** [comment]
Okay. it is understood . Thanks a lot.

**Comment by cyp3rius** [comment]
You are welcome :)
